# Uncomment this line to define a global platform for your project
platform :ios, '9.0'

target 'PCast Demo' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PCast Demo
  pod 'Fabric'
  pod 'Crashlytics'
  pod 'ReachabilitySwift', '~> 3'
  pod 'TPKeyboardAvoiding'

end
